name: weather_forecast_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.2+13

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_it: ^7.7.0
  google_mobile_ads: ^5.1.0
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#042C4C"

  android_12:
    color: "#042C4C"

flutter:
  uses-material-design: true

  assets:
  - environment/
  - assets/
  - assets/icons/
  - assets/fonts/
  - assets/logos/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200        
        - asset: assets/fonts/Nunito-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
