name: weather_forecast_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.4+15

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_analytics: ^11.3.6
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.2
  google_mobile_ads: ^5.2.0
  intl: ^0.20.1
  package_info_plus: ^8.1.1
  shared_preferences: ^2.3.3
  share_plus: ^10.1.2
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - environment/
  - assets/
  - assets/icons/
  - assets/fonts/
  - assets/logos/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200        
        - asset: assets/fonts/Nunito-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
