name: weather_forecast_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  get_it: ^7.7.0
  intl: ^0.19.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#042C4C"

  android_12:
    color: "#042C4C"

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/
  - assets/icons/
  - assets/fonts/
  - assets/logos/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200        
        - asset: assets/fonts/Nunito-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
