name: weather_forecast_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.6+17

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  google_mobile_ads: ^6.0.0
  intl: ^0.19.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  share_plus: ^11.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - environment/
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
          
flutter_intl:
  enabled: true
